src/config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  root 'static_pages#home'
  get '/help',      to: "static_pages#help"
  get '/about',     to: "static_pages#about"
  get '/contact',   to: "static_pages#contact"
  get '/signup',    to: "users#new"
  get '/login',     to: "sessions#new"
  post '/login',    to: "sessions#create"
  delete '/logout', to: "sessions#destroy"

  resources :users do
    member do     # idを含む=>member routing , idを含まない=>colloection routing
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]

end

# root_path -> '/'
# root_url  -> 'https://www.rspec-exercise-sho.herokuapp.com/'
# 基本的には_path書式を使い、リダイレクトの場合のみ_url書式を使う

# resources :users の内容
# HTTPリクエスト	URL	アクション	名前付きルート	    用途
# GET	    /users	      index	  users_path	          すべてのユーザーを一覧するページ
# GET	    /users/1	    show	  user_path(user)	      特定のユーザーを表示するページ
# GET	    /users/new	  new	    new_user_path	        ユーザーを新規作成するページ（ユーザー登録）
# POST	  /users	      create	users_path	          ユーザーを作成するアクション(メール送信)
# GET	    /users/1/edit	edit	  edit_user_path(user)	id=1のユーザーを編集するページ
# PATCH	  /users/1	    update	user_path(user)	      ユーザーを更新するアクション
# DELETE	/users/1	    destroy	user_path(user)	      ユーザーを削除するアクション

# GET   /users/1/following  following   following_user_path(1)
# GET   /users/1/followers  followers   followers_user_path(1)

# resources :account_activations の内容
# GET	    /account_activation/トークン/edit	  edit	  edit_account_activation_path(token)	

# resources :password_resets の内容
# GET	  /password_resets/new	          new	    new_password_reset_path     (log in前)forgetパスワード画面の表示
# POST	/password_resets	              create  password_resets_path        forgetパスワードメール送付
# GET	  /password_resets/トークン/edit	edit	  edit_password_reset_url(token)  
# PATCH	/password_resets/トークン	      update	password_reset_url(token)

# resources :microposts の内容
# POST	  /microposts	    create	  microposts_path
# DELETE	/microposts/1	  destroy	  micropost_path(micropost)

# resources :relationships の内容
# POST	  /relationships	    create	  relationships_path
# DELETE	/relationships/1	  destroy	  relationship_path(1)

src/app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  before_action :get_user,          only: [:edit, :update]
  before_action :valid_user,        only: [:edit, :update]
  before_action :check_expiration,  only: [:edit, :update]    # reset_mailの期限確認

  def new   # forget_passwordの画面表示
  end

  def create  # forget_passwordリセットのmail送信
    @user = User.find_by(email: params[:password_reset][:email].downcase)
    if @user
      @user.create_reset_digest   # reset_digestとreset_tokenの生成
      @user.send_password_reset_email   # reset_mailの送付
      flash[:info] = "Email sent with password reset instructions"
      redirect_to root_url
    else
      flash.now[:danger] = "Email address not found"
      render "new"  # PasswordResets#newへ。
    end
  end

  def edit  # mailのリンクをクリックしたときのアクション。
  end
  
  def update  # mailのリンクから遷移したreset_passwordの画面でpassword再設定
    if params[:user][:password].empty?
      @user.errors.add(:password, :blank)   # passwordが空欄でないことを確認
      render "edit"
    elsif @user.update(user_params)
      log_in @user
      flash[:success] = "Password has been reset."
      redirect_to @user
    else                 # passwordが正しくない場合
      render "edit"
    end
  end

  private

    def user_params
      params.require(:user).permit(:password, :password_confirmation)
    end
    
    def get_user
      @user = User.find_by(email: params[:email])
    end

    def valid_user
      unless (@user && @user.activated? && @user.authenticated?(:reset, params[:id]) )
        # params[:id]は@user.reser_token(参照:views\user_mailer\password_reset.html.erb)であるはず
        redirect_to root_url
      end
    end

    def check_expiration
      if @user.password_reset_expired?
        flash[:danger] = "Password reset has expired."
        redirect_to new_password_reset_url
      end
    end

end

src/app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

src/app/views/password_resets/edit.html.erb
<% provide(:title, "Reset password") %>
<h1>Reset password</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
  <%# patch password_reset_path(token), to: password_resets#update  %>
    <%= form_with(model: @user, url: password_reset_path(params[:id]), local: true) do |f| %>

      <%= render "shared/error_messages", object: f.object%>

      <%= hidden_field_tag :email, @user.email %>
      <%# input id="email" name="email" type="hidden" value="@user.email" %>
      <%# => params[:email]で取り出せる %>
      <%# ※f.hidden_field の場合はmodelに紐づくため、 params[:user][:email]で取り出せる %>

      <%= f.label :password %>
      <%= f.password_field :password, class: "form-control" %>
      <%# label for="password_reset_email" %>
      <%# input id="password_reset_email name="password_reset[email]" type="email %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: "form-control" %>

      <%= f.submit "Update password", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

src/app/views/password_resets/new.html.erb
<% provide(:title, "Forget password") %>
<h1>Forget password</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
  <%# 特定のモデルと結びつかない時はmodelではなくscope + url %>
  <%# post password_resets_path, to: password_resets#create  %>
    <%= form_with(url: password_resets_path, scope: :password_reset, local: true) do |f| %>

      <%= f.label :email %>
      <%= f.email_field :email, class: "form-control" %>
      <%# label for="password_reset_email" %>
      <%# input id="password_reset_email name="password_reset[email]" type="email %>

      <%= f.submit "Submit", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>