src/config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  root 'static_pages#home'
  get '/help',      to: "static_pages#help"
  get '/about',     to: "static_pages#about"
  get '/contact',   to: "static_pages#contact"
  get '/signup',    to: "users#new"
  get '/login',     to: "sessions#new"
  post '/login',    to: "sessions#create"
  delete '/logout', to: "sessions#destroy"

  resources :users do
    member do     # idを含む=>member routing , idを含まない=>colloection routing
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]

end

# root_path -> '/'
# root_url  -> 'https://www.rspec-exercise-sho.herokuapp.com/'
# 基本的には_path書式を使い、リダイレクトの場合のみ_url書式を使う

# resources :users の内容
# HTTPリクエスト	URL	アクション	名前付きルート	    用途
# GET	    /users	      index	  users_path	          すべてのユーザーを一覧するページ
# GET	    /users/1	    show	  user_path(user)	      特定のユーザーを表示するページ
# GET	    /users/new	  new	    new_user_path	        ユーザーを新規作成するページ（ユーザー登録）
# POST	  /users	      create	users_path	          ユーザーを作成するアクション(メール送信)
# GET	    /users/1/edit	edit	  edit_user_path(user)	id=1のユーザーを編集するページ
# PATCH	  /users/1	    update	user_path(user)	      ユーザーを更新するアクション
# DELETE	/users/1	    destroy	user_path(user)	      ユーザーを削除するアクション

# GET   /users/1/following  following   following_user_path(1)
# GET   /users/1/followers  followers   followers_user_path(1)

# resources :account_activations の内容
# GET	    /account_activation/トークン/edit	  edit	  edit_account_activation_path(token)	

# resources :password_resets の内容
# GET	  /password_resets/new	          new	    new_password_reset_path     (log in前)forgetパスワード画面の表示
# POST	/password_resets	              create  password_resets_path        forgetパスワードメール送付
# GET	  /password_resets/トークン/edit	edit	  edit_password_reset_url(token)  
# PATCH	/password_resets/トークン	      update	password_reset_url(token)

# resources :microposts の内容
# POST	  /microposts	    create	  microposts_path
# DELETE	/microposts/1	  destroy	  micropost_path(micropost)

# resources :relationships の内容
# POST	  /relationships	    create	  relationships_path
# DELETE	/relationships/1	  destroy	  relationship_path(1)

src/app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="https://railstutorial.jp/">Ruby on Rails Tutorial</a>
    by <a href="https://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="https://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

src/app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "sample app", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   root_path %></li> <%# => <a href="#">Home</a> %>
        <li><%= link_to "Help",   help_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account<b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>

      </ul>
    </nav>
  </div>
</header>

src/app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= csp_meta_tag %>
<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<% # =  stylesheet_link_tag('application', { media: 'all','data-turbolinks-track': 'reload'} ) %>
<% # => link rel="stylesheet" media="all" href="/assets/application.self-f0d704deea029cf000697e2c0181ec173a1b474645466ed843eb5ee7bb215794.css?body=1"data-turbolinks-track="reload" %>
<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

src/app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

src/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= render 'layouts/rails_default' %>
  <%= render 'layouts/shim' %>
</head>

<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
      <%# = content_tag(:div, value, class: "alert alert-#{key}") %>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development?%>
  </div>

</body>

</html>